
#Config to adjust general mod settings
[General]
	#Enables the debug mode. Only enable it if needed.
	enableDebugMode = false

[Core]
	#Enables initial cooldown on peripheral initialization
	isInitialCooldownEnabled = true
	#Determinates initial cooldown sensitive level, values lower then this value will not trigger initial cooldown
	#Range: > 0
	initialCooldownSensitiveLevel = 6000

[Unsafe]
	#By setting this value to true, I understand all operations below are danger to my adventure, and if they caused unexpected behavior in my world, I will not consider it as AP's liability
	enableUnsafe = false
	#Ignore turtle peripheral item's NBT when equipping. **YOU WILL LOSE ALL NBT ON THE ITEM**
	ignoreTurtlePeripheralItemNBT = false

