#Should JSG check for update on startup?
#SIDE: CLIENT
"Check for updates" = false
#Specifies transparency of glyphs on notebook page
#SIDE: CLIENT
#Range: 0.0 ~ 1.0
"Notebook page Glyph transparency" = 0.75
#Greater values render the Page more to the center of the screen, smaller render it closer to the borders.
#0 - for standard 16:9 (default),
#0.2 - for 4:3.
#SIDE: CLIENT
#Range: 0.0 ~ 1.0
"Notebook Page offset" = 0.0
#Render light of some textures.
#Disable this if it causes lags.
#SIDE: CLIENT
"Render emissive textures" = true
#SIDE: CLIENT
"Change title to w/ JSG" = true
#Disable fadeout when going through a gate or using transport rings or victim of Destiny FTL jump
#SIDE: CLIENT
"Disable white fadeout" = false
#Specifies what unit will be used to display temperatures
#SIDE: CLIENT
#Allowed Values: KELVIN, CELSIUS, FAHRENHEITS
"Temperature unit" = "CELSIUS"
#SIDE: CLIENT
#Range: 0 ~ 100
"Destiny CO2 blaster particles count/tick" = 5
#SIDE: SERVER
"Enable teleports using End Portal" = false
#SIDE: SERVER
"Enable teleports using Nether Portal" = false
#Disables showing custom main menu
#WARNING! - Requires reloading!
#SIDE: CLIENT
"Disable JSG main menu" = true
#Specifies how many images can be used as background of mainmenu. (starts from 0)
#DO NOT CHANGE THIS IF YOU DO NOT KNOW WHAT ARE YOU DOING!
#WARNING! - Requires reloading!
#SIDE: CLIENT
"Main menu background images count" = 7
#WARNING! - Requires reloading!
#SIDE: CLIENT
"Enable Tau'ri logo on startup" = false
#SIDE: CLIENT
"Enable debug mode in main menu" = false
#SIDE: CLIENT
"Play music in main menu" = false
#SIDE: CLIENT
"Play loading music" = false

