blank_issues_enabled: false
contact_links:
  - name: TerraFirmaGreg Discord
    url: https://discord.gg/AEaCzCTUwQ
    about: Join us on Discord to discuss questions, bugs, and more.
    
  - name: TerraFirmaGreg CurseForge
    url: https://www.curseforge.com/minecraft/modpacks/terrafirmagreg-modern
    about: Download page.

  - name: TerraFirmaGreg YouTube
    url: https://www.youtube.com/@TFG-modern
    about: YouTube channel.
