#Whether to allow factory gauges cascade ingredient requests
factoryGaugeCascadeRequest = true
#Capacity of the jar in millibuckets
#Range: 1 ~ 999999999
jarCapacity = 8000
#Whether jar packager (bottler) should pick output tanks over combined. Useful if you want to keep basin inputs intact
jarPackagerPrefersOutputs = true

