
[general]
	#If false, sprinklers will not accept Firmalife pipes and will instead require something that exposes a fluid capability, eg. a barrel.
	usePipesForSprinklers = false
	#Days in a cellar to make cheese Aged.
	#Range: > 1
	cheeseAgedDays = 28
	#Days in a cellar to make cheese Vintage.
	#Range: > 1
	cheeseVintageDays = 112
	#Ticks to dry something on a drying mat (24000 ticks = 1 day)
	#Range: > 1
	dryingTicks = 12000
	#Ticks to dry something on a solar drier (24000 ticks = 1 day)
	#Range: > 1
	solarDryingTicks = 1000
	#Ticks to smoke something on a string (24000 ticks = 1 day)
	#Range: > 1
	smokingTicks = 8000
	#Number of blocks below the firepit that wool string will search for valid smoking firepits.
	#Range: > 1
	smokingFirepitRange = 6
	#Ticks for a composter tumbler to finish (24000 ticks = 1 day)
	#Range: > 1
	compostTumblerTicks = 96000
	#Ticks for an oven to cure (24000 ticks = 1 day)
	#Range: > 1
	ovenCureTicks = 2000
	#Minimum temperature for an oven to start the curing process (24000 ticks = 1 day)
	#Range: > 1
	ovenCureTemperature = 600
	#If true, ovens will hurt the player if they touch it without a peel in hand.
	ovenRequirePeel = false
	#The chance for fuel burning in an oven to drop an ash block into an ashtray.
	#Range: 0.0 ~ 1.0
	ovenAshChance = 0.5
	#If true, players can throw seed balls.
	enableSeedBalls = true
	#If true, bees can swarm and hurt the player if provoked.
	enableBeeSwarm = true
	#The capacity in mB of the wine glass. Default 250
	#Range: > 1
	hollowShellCapacity = 250
	#The average temperature below which stronger decay modifiers apply to cellar blocks.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	cellarLevel2Temperature = 0.0
	#The average temperature below which even stronger decay modifiers apply to cellar blocks.
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	cellarLevel3Temperature = -12.0
	#The average amount of days for a crop in a greenhouse to grow. For normal crops, this is 24 days.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	greenhouseGrowthDays = 20.0
	#The average amount of days for a crop in a greenhouse to consume all its water.
	#Range: 0.0 ~ 1.7976931348623157E308
	greenhouseWaterDays = 12.0
	#The average amount of days for a crop to consume all of a nutrient. You should probably not configure this value unless you know what it does in the code. For regular crops this value is 12.
	#Range: 0.0 ~ 1.7976931348623157E308
	greenhouseNutrientDays = 8.0
	#The max bounded distance from the climate station a greenhouse wall can be. Higher numbers = more lag.
	#Range: 1 ~ 128
	greenhouseRadius = 15
	#The max bounded distance from the climate station a cellar wall can be. Higher numbers = more lag.
	#Range: 1 ~ 128
	cellarRadius = 15
	#If true, the tumbler and the pumping station work magically with a redstone signal and no power required.
	mechanicalPowerCheatMode = true

[foodTraits]
	#The modifier for the 'Dried' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitDriedModifier = 0.5
	#The modifier for the 'Fresh' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitFreshModifier = 1.100000023841858
	#The modifier for the 'Aged' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitAgedModifier = 0.8999999761581421
	#The modifier for the 'Vintage' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitVintageModifier = 0.6000000238418579
	#The modifier for the 'Oven_baked' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitOven_bakedModifier = 0.8999999761581421
	#The modifier for the 'Smoked' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitSmokedModifier = 0.699999988079071
	#The modifier for the 'Rancid_smoked' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitRancid_smokedModifier = 2.0
	#The modifier for the 'Shelved' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitShelvedModifier = 0.4000000059604645
	#The modifier for the 'Shelved_2' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitShelved_2Modifier = 0.3499999940395355
	#The modifier for the 'Shelved_3' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitShelved_3Modifier = 0.25
	#The modifier for the 'Hung' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitHungModifier = 0.3499999940395355
	#The modifier for the 'Hung_2' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitHung_2Modifier = 0.30000001192092896
	#The modifier for the 'Hung_3' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitHung_3Modifier = 0.25
	#The modifier for the 'Fermented' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitFermentedModifier = 0.25
	#The modifier for the 'Bee_pollinated' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitBee_pollinatedModifier = 0.800000011920929
	#The modifier for the 'Dirt_grown' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitDirt_grownModifier = 0.8999999761581421
	#The modifier for the 'Gravel_grown' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitGravel_grownModifier = 0.800000011920929
	#The modifier for the 'Slope_grown' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitSlope_grownModifier = 0.800000011920929

