
[Data]
	#Generate all the potential Material Items, even if they're unused - Default: false
	ALL_MATERIAL_ITEMS = false

[World]
	#Disable Vanilla ore generation (Iron Ore, Diamond Ore etc) - Default: true
	DISABLE_VANILLA_ORE_GEN = true
	#Disable vanilla stone generation (Granite, Diorite etc) - Default: true
	DISABLE_VANILLA_STONE_GEN = true
	#Enable small ores - Default: true
	SMALL_ORES = true
	#Enable surface rocks - Default: true
	SURFACE_ROCKS = true
	#Shows ore veins very clearly in spectator mode - Default: false
	ORE_VEIN_SPECTATOR_DEBUG = true

	[World."Ore Veins"]
		#Enable ore veins - Default: true
		ORE_VEINS = true
		#Maximum size of an ore vein - Default: 32
		#Range: > 1
		ORE_VEIN_MAX_SIZE = 32
		#Control percentage of filled 3x3 chunks. Lower number means less ore veins would spawn - Default : 100
		#Range: > 1
		ORE_VEIN_CHANCE = 100
		#Chance of ore veins having surface rocks - Default: 256
		#Range: > 1
		ORE_VEIN_ROCK_CHANCE = 256
		#Control number of attempts to find a valid ore vein,
		#Generally this maximum limit isn't hit, as selecting a vein is performant - Default : 64
		#Range: > 1
		ORE_VEIN_FIND_ATTEMPTS = 64
		#Control number of attempts to place a valid ore vein,
		#If a vein wasn't placed due to height restrictions, completely in the water, or other criterion, another attempt is tried - Default : 8
		#Range: > 1
		ORE_VEIN_PLACE_ATTEMPTS = 8
		#Enable ore vein's having small ores as markers/indicators - Default: true
		ORE_VEIN_SMALL_ORE_MARKERS = true
		#Multiplier to control how many small ore markers get generated per vein - Default : 2
		#Range: > 1
		ORE_VEIN_SMALL_ORE_MARKERS_MULTI = 2

	[World."Stone Layers"]
		#Enable stone layers - Default: false
		STONE_LAYERS = false
		#Enable stone layers having ores - Default: false
		STONE_LAYER_ORES = false
		#Chance of stone layers having surface rocks - Default: 128
		#Range: > 1
		STONE_LAYER_ROCK_CHANCE = 128

[Gameplay]
	#Whether or not to reconsume recipe inputs on multiblock failure - Default : false
	INPUT_RESET_MULTIBLOCK = false
	#Amount of gas retained passing through a leaky pipe - Default: 90%
	#Range: 0.0 ~ 1.0
	PIPE_LEAK = 0.9
	#Enable hardcore cable loss and voltage - Default: true
	HARDCORE_CABLES = true
	#Enable pipe blowing on overpressure - Default: false
	HARDCORE_PIPES = false
	#Hear various crafting sounds when you craft with any of Antimatter's tools that has a custom SoundType. Default: true
	PLAY_CRAFTING_SOUNDS = true
	#Enable crating recipes for things like rods and plates being lossy - Default: true
	#Note: make sure to run /reload after changing this.
	LOSSY_PART_CRAFTING = true

	[Gameplay.Treefelling]
		#Smart tree detection, instead of just going up in a column, it searches surrounding connected blocks too. Default: true
		SMARTER_TREE_DETECTION = true
		#Allow Antimatter Axe types to fell trees - Default: true
		AXE_TIMBER = true
		#Max height of a column of logs an Antimatter Axe type can fell - Default: 100
		#Range: 1 ~ 2304
		AXE_TIMBER_MAX = 100

["Mod Compatibility"]
	#Enable all mod support registrars - Default: true
	ENABLE_ALL_REGISTRARS = true

