
[general]
	#Enable debug mode?
	enableDebug = false

[worldmap]
	#List of disabled Layers, comma separated
	activeMap = "cartography:geology"
	#List of disabled Layers, comma separated
	disabledLayers = []
	#Zoom level. Must be a power of 2
	#Range: 0.25 ~ 16.0
	zoom = 4.0

[minimap]
	#List of disabled Layers, comma separated
	activeMap = "blazemap:aerial_view"
	#List of disabled Layers, comma separated
	disabledLayers = []
	#Zoom level. Must be a power of 2
	#Range: 0.5 ~ 8.0
	zoom = 1.0
	#Overlay size
	#Allowed Values: SMALL, MEDIUM, LARGE, HUGE
	overlaySize = "LARGE"
	#Enable the minimap?
	enabled = true

