
##Waterwheel requirements
[waterwheels]
	#Enable waterwheels modifications?
	waterwheelsEnabled = true
	#The minimum amount of fluid blocks the waterwheel needs to find before rotation begins.
	#Range: > 1
	waterwheelThreshold = 3200
	#The maximum distance a waterwheel can consider fluid blocks from.
	#Range: > 1
	waterwheelRange = 128

##Windmill requirements
[windmills]
	#Enable windmills modifications?
	windmillsEnabled = true
	#The minimum floor area required. Default: 1/4 of the max area [PI * 32 ^ 2]
	#Range: > 1
	windmillThreshold = 804
	#The minimum length of air current required.
	#Range: > 1
	windmillRequiredRange = 24
	#The minimum amount of points that must hit windmillRequiredRange.
	#Range: > 1
	windmillRequiredRangePoints = 128
	#The maximum distance a waterwheel can consider air blocks from.
	#Range: > 1
	windmillMaxRange = 32
	#The multiplier for the benefit given for raised windmills.
	#Range: > 1
	windmillAboveX = 4
	#The height required for the full benefit from windmillAboveX.
	#Range: > 1
	windmillAbove = 16

