#.
#Migrate copycats to Create: Copycats+ when they receive a block update
migrateCopycatsOnBlockUpdate = false
#.
#Migrate copycats to Create: Copycats+ when their block entities are initialized
migrateCopycatsOnInitialize = false

#.
#Enable/disable features. Values on server override clients
[features]
	item_silo = true
	inverted_clutch = true
	empty_fan_catalyst = false
	parallel_gearbox = false
	centrifugal_clutch = true
	copycat_slab = true
	overstress_clutch = true
	brake = true
	copycat_block = true
	copycat_fence_gate = true
	copycat_stairs = true
	brass_gearbox = false
	copycat_vertical_step = true
	copycat_wall = true
	six_way_gearbox = false
	encased_chain_cogwheel = false
	sequenced_pulse_generator = true
	freewheel_clutch = true
	shear_pin = false
	inverted_gearshift = false
	linked_transmitter = true
	copycat_beam = true
	copycat_board = true
	copycat_fence = true
	fluid_vessel = true
	large_crank_wheel = false
	crank_wheel = false
	inventory_access_port = true
	inventory_bridge = true
	#.
	kinetic_bridge = true
	cross_connector = true
	redstone_link_wildcard = true
	kinetic_battery = true

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#.
	#All kinetic components, such as gearboxes and crank wheels
	kinetic = true
	#.
	#All redstone components, such as linked transmitter and sequenced pulse generator
	redstone = true
	#.
	#All components related to item and fluid transport
	logistics = true
	#.
	#All copycats (Install Create: Copycats+ to upgrade)
	copycats = true
	#.
	#All building palette blocks
	palette = true

