
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = false
	#Don't touch unless you are told to
	debug_packet = false
	#Enables the generation of dynamic assets. This is required for the mod to work properly. Turn off if you chose to add all the generated assets via datapack manually. This can speedup boot times for modpacks. Note that the generated assets will depend on loaded datapacks
	generate_dynamic_assets = true
	#Allow the item_search or searchBar to be visible.
	tab_item_search = true

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

