
#    ═════════════════════════ Attention ═════════════════════════
#    Don't use this if you don't know what you are doing
#        REASON:
#    This file is a conditional registration. This is harmless in Singleplayer World,
#    but harmful in SERVER because you won't able to join.
#
#    ══════════════════════════ Detail ═══════════════════════════
#    This file allow you to exclude WoodTypes, LeavesType, EntrySet, or a Module
#    1) You can find their names for WoodTypes, LeavesType, or EntrySet in `everycomp-entries.toml`
#    2) Leave a value empty to disable that rule.
#
#    Module - is a Supported Mod, just a modId is sufficient.
#    EntrySet - is a FurnitureType or DecorativeType that Wood-Good is supporting via the mod. it is either block or item.
#    Wood-Mods - Biomes O' Plenty, The Twilight Forest, so on...
#    Supported-Mods - The mods that EveryCompat is currently supporting
#
#    NOTE: blacklisting a Module will be applied to Wood-Good, Stone-Zone, Gems-Realm
#
[woodtype]
	#Exclude WoodType from all of Modules
	#    EXAMPLE: blacklist = [
	#        "forestry:.*fireproof.*",		COMMENT: .* is an RegEx, it exclude all of WoodType containing "fireproof" from Forestry
	#        "biomesoplenty:.*",			COMMENT: .* is an RegEx, it exclude all of WoodType from Wood Mod for any Module
	#        "biomesoplenty:redwood"		COMMENT: exclude redwood from Wood Mod for any module
	#    ]
	#
	blacklist = []

[leavestype]
	#Exclude LeavesType from all of Modules
	#	The example is same as WoodType's
	blacklist = []

[entryset]
	#Exclude EntrySet from the module for All of WoodType or LeavesType
	#    This is only applied to Wood-Good.
	#    EXAMPLE: blacklist = [
	#        "chipped:checkered_trapdoor",		COMMENT: chipped:checkered_oak_trapdoor without "oak"
	#        "variantvanillablocks:chest",		COMMENT: variantvanillablocks:oak_chest without "oak"
	#        "chipped:.*"						COMMENT: .* is an regex which will exclude all of EntrySets from one Module - Wood-Good ONLY
	#    ]
	#    NOTE: This excluded one entryset from all WoodTypes/LeavesTypes
	#
	blacklist = []

[module]
	#Exclude Module From Wood-Good, Stone-Zone & Gems-Realm
	#    EXAMPLE: blacklist = [
	#        "chipped",
	#        "variantvanillablocks"
	#    ]
	#
	blacklist = []

[block]
	#Exclude a specific WoodType/LeavesType block
	#    This is only applied to Wood-Good.
	#    EXAMPLE: blacklist = [
	#        "chipped/biomesoplenty/checkered_redwood_trapdoor",	COMMENT: excluded a checkered_trapdoor from Chipped with Biomes-O'-Plenty's redwood
	#        "variantvanillablocks/biomesoplenty/fir_chest",		COMMENT: excluded a chest from Variant-Vanilla-Blocks with Biomes-O'-Plenty's fir
	#        ".*/biomesoplenty/fir_chest",							COMMENT: .* is an RegEx, so it exclude fir_chest from any Supported-Mods with just Biomes-O'-Plenty (Wood-Mods)
	#        "chipped/.*/fir_chest",								COMMENT: .* is an RegEx, so it exclude fir_chest from any Wood-Mods with just chipped (Supported-Mod)
	#        ".*fir_chest",											COMMENT: .* is an RegEx, so it exclude fir_chest from any Supported-Mods & Wood-Mods
	#    ]
	#
	blacklist = []

[other]
	#Disable all of Supported Mods on EveryCompat's side. This feature is same as Library-Section which do not have any Wood Modules.
	#WARNING: If the config between CLIENT & SERVER are not the same, then you won't able to join a server
	include_all_wood_modules = true

