
#Client only settings, mostly things related to rendering
[client]
	#Enable Forge to queue all chunk updates to the Chunk Update thread.
	#May increase FPS significantly, but may also cause weird rendering lag.
	#Not recommended for computers without a significant number of cores available.
	alwaysSetupTerrainOffThread = false
	#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = false
	#When enabled, Forge will show any warnings that occurred during loading.
	showLoadWarnings = true
	#Set to true to use a combined DEPTH_STENCIL attachment instead of two separate ones.
	useCombinedDepthStencilAttachment = false
	#[DEPRECATED] Does nothing anymore, IPv6 addresses will be compressed always
	compressLanIPv6Addresses = true

