# Enable/Disable wire coating recipes in the crafting grid/packer/assembler.
# If disabled, wire coating recipes will only be accessible via the spout & wire coating factory.
enableGTWireCoatingRecipes: true

# Enable/Disable harder recipes for various Create blocks & items.
enableHardCreateRecipes: false

# Should certain Create items that have a GTCEu counterpart be used in recipes?
# If false, GTCEu items will be used instead.
useCreateItemsInRecipes: false

# Should recipes from create that conflict with GTCEu recipes be enabled?
# [WARNING]: This will not cover every single recipe conflict, only common conflicts (like components (plates/sheets)), or ore processing conflicts.
disableConflictingRecipes: true

# Should tiered encased fans process item entities?
processItemEntitiesWithFan: false

# Should recipes that cannot be removed be logged?
logUnremovableRecipes: true

# "Multiplier used for calculating how many ticks should initially be removed in fan processing recipes, based on how fast the fan is spinning."
fanSpeedMultiplier: 0.5

# Recipe types that should not be copied to Greate machines. Ex. 'gtceu:macerator' for macerator recipes
ignoredRecipeTypes:
  - gtceu:ore_washer
  - gtceu:bender
  - gtceu:compressor

