
[default]
	#quad expansion increment. enlarges each quad. Use to hide gaps. Keep both as close to 0 as possible. Note that increasing it to non 0 will slightly increase the amount of quads per item model. Could be an issue with HD texture packs.Try these values: 0.002 or 0.008
	#Range: -0.1 ~ 0.1
	item_quads_expansion = 0.0
	#quad x/y offset. simply put moves the quad toward the center of the item. Use to hide gaps
	#Range: -0.1 ~ 0.1
	item_quads_indent = 0.007

[mac_os]
	#set to 0 for non macos behavior. 1 keeps vanilla behavior to prevent atlas bleeding
	#Range: 0.0 ~ 1.0
	shrink_ratio_multiplier = 1.0
	#It has been reported that some mac os systems are affected by atlas bleeding so the mod cant apply its main fix by removing atlas shrinking. Instead it can reduce it as much as possible by multiplying it by shrink_value_multiplier
	#quad expansion increment. enlarges each quad. Use to hide gaps. Keep both as close to 0 as possible. Note that increasing it to non 0 will slightly increase the amount of quads per item model. Could be an issue with HD texture packs
	#Range: -0.1 ~ 0.1
	item_quads_expansion = 0.0
	#quad x/y offset. simply put moves the quad toward the center of the item. Use to hide gaps
	#Range: -0.1 ~ 0.1
	item_quads_indent = 0.0099

