
[general]
	# If the TFC world type (tfc:tng) should be set as the default world generation.
	# 1. This ONLY sets the corresponding config option in Forge's config.
	# 2. This ONLY will set the default if it was set to 'default' (or vanilla generation)
	# 3. This DOES NOT guarantee that the world generation will be TFC, if another mod sets the default another way
	setTFCWorldTypeAsDefault = true

[calendar]
	# The number of days in a month, for newly created worlds.
	# This can be modified in existing worlds using the /time command
	#Range: > 1
	defaultMonthLength = 8
	# The start date for newly created worlds, in a number of ticks, for newly created worlds
	# This represents a number of days offset from January 1, 1000
	# The default is (5 * daysInMonth) = 40, which starts at June 1, 1000 (with the default daysInMonth = 8)
	#Range: > -1
	defaultCalendarStartDay = 40

[debug]
	# Enables a series of network fail-safes that are used to debug network connections between client and servers.
	# Important: this MUST BE THE SAME as what the server has set, otherwise you are liable to see even stranger errors.
	enableNetworkDebugging = false

