#How dark should the noise be at most? Set to 0 to disable noise entirely
#Range: 0.0 ~ 0.5
noiseDarkness = 0.18
#How many darkness levels should there be?
#Range: 5 ~ 30
noiseLevels = 5
#How big should noise areas be?
#Range: 3 ~ 50
noiseArea = 10
#ARGB code for summer coloring in hexadecimal. Default: 1222FF11
seasonColorSummer = "1233FF11"
#ARGB code for autumn coloring in hexadecimal. Default: EAFFDD55
seasonColorAutumn = "EAFFDD55"
#ARGB code for winter coloring in hexadecimal. Default: 6AFFEEEE
seasonColorWinter = "6AFFEEEE"
#ARGB code for spring coloring in hexadecimal. Default: 3311CFD1
seasonColorSpring = "3311CAD7"
#How much to drip when wet. 0 to turn off
#Range: 0 ~ 100
drippiness = 30
#For all ARGB values, set to 00000000 to disable the feature in that season
#Change temperature display to Fahrenheit.
useFahrenheit = false
#Offset the GUI elements. Useful if you're using a resourcep ack that changes the health or hunger bars
#Range: 0.0 ~ 3.4028234663852886E38
guiOffset = 8.0

